# Generated by Django 5.0.2 on 2024-02-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_spectr', models.CharField(max_length=3)),
                ('values_x', models.TextField()),
                ('values_y', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spectr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(unique=True)),
                ('chemical_name', models.TextField(blank=True)),
                ('values_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.values')),
            ],
        ),
    ]
