# Generated by Django 5.0.2 on 2024-02-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spectr',
            options={'verbose_name': 'Спектр', 'verbose_name_plural': 'Спектры'},
        ),
    ]
